INSERT INTO system_configs (id, config_key, config_value, description, updated_by, updated_at)
VALUES
  ('cfg_oss_provider', 'oss.provider', 'QINIU', '对象存储服务商', 'system', NOW()),
  ('cfg_oss_enabled', 'oss.enabled', 'false', '对象存储总开关', 'system', NOW()),
  ('cfg_oss_qiniu_access_key', 'oss.qiniu.access_key', '', '七牛云AccessKey', 'system', NOW()),
  ('cfg_oss_qiniu_secret_key', 'oss.qiniu.secret_key', '', '七牛云SecretKey', 'system', NOW()),
  ('cfg_oss_qiniu_bucket', 'oss.qiniu.bucket', '', '七牛云存储空间Bucket', 'system', NOW()),
  ('cfg_oss_qiniu_domain', 'oss.qiniu.domain', '', '七牛云访问域名', 'system', NOW()),
  ('cfg_oss_qiniu_region', 'oss.qiniu.region', 'z0', '七牛云存储区域', 'system', NOW()),
  ('cfg_oss_qiniu_path_prefix', 'oss.qiniu.path_prefix', 'uploads/', '七牛云对象前缀', 'system', NOW()),
  ('cfg_oss_qiniu_use_https', 'oss.qiniu.use_https', 'true', '七牛云访问是否启用HTTPS', 'system', NOW()),
  ('cfg_oss_upload_max_size_mb', 'oss.upload.max_size_mb', '20', '上传文件最大大小(MB)', 'system', NOW()),
  ('cfg_oss_upload_allowed_exts', 'oss.upload.allowed_exts', 'jpg,jpeg,png,gif,webp,pdf,doc,docx,xls,xlsx,ppt,pptx,zip', '允许上传扩展名，逗号分隔', 'system', NOW()),
  ('cfg_payment_enabled', 'payment.enabled', 'false', '平台支付总开关', 'system', NOW()),
  ('cfg_payment_default_channel', 'payment.default_channel', 'ALIPAY', '默认支付通道', 'system', NOW()),
  ('cfg_payment_signing_secret', 'payment.signing_secret', '', '支付回调签名密钥', 'system', NOW()),
  ('cfg_payment_order_timeout', 'payment.order_timeout_minutes', '30', '支付订单超时时间(分钟)', 'system', NOW()),
  ('cfg_payment_alipay_enabled', 'payment.channel.alipay.enabled', 'false', '支付宝通道开关', 'system', NOW()),
  ('cfg_payment_alipay_app_id', 'payment.channel.alipay.app_id', '', '支付宝应用ID', 'system', NOW()),
  ('cfg_payment_alipay_mch_id', 'payment.channel.alipay.merchant_id', '', '支付宝商户号', 'system', NOW()),
  ('cfg_payment_alipay_private_key', 'payment.channel.alipay.private_key', '', '支付宝应用私钥', 'system', NOW()),
  ('cfg_payment_alipay_public_key', 'payment.channel.alipay.public_key', '', '支付宝公钥', 'system', NOW()),
  ('cfg_payment_alipay_notify_url', 'payment.channel.alipay.notify_url', '', '支付宝异步通知地址', 'system', NOW()),
  ('cfg_payment_wechat_enabled', 'payment.channel.wechat.enabled', 'false', '微信支付通道开关', 'system', NOW()),
  ('cfg_payment_wechat_mch_id', 'payment.channel.wechat.mch_id', '', '微信支付商户号', 'system', NOW()),
  ('cfg_payment_wechat_app_id', 'payment.channel.wechat.app_id', '', '微信支付应用ID', 'system', NOW()),
  ('cfg_payment_wechat_api_v3_key', 'payment.channel.wechat.api_v3_key', '', '微信支付APIv3密钥', 'system', NOW()),
  ('cfg_payment_wechat_cert_serial_no', 'payment.channel.wechat.cert_serial_no', '', '微信支付证书序列号', 'system', NOW()),
  ('cfg_payment_wechat_private_key', 'payment.channel.wechat.private_key', '', '微信支付私钥', 'system', NOW()),
  ('cfg_payment_wechat_notify_url', 'payment.channel.wechat.notify_url', '', '微信支付异步通知地址', 'system', NOW())
ON DUPLICATE KEY UPDATE
  description = VALUES(description),
  updated_by = VALUES(updated_by),
  updated_at = VALUES(updated_at);
