CREATE TABLE IF NOT EXISTS stock_selection_runs (
  run_id varchar(64) NOT NULL,
  trade_date date NOT NULL,
  job_id varchar(64) DEFAULT NULL,
  profile_id varchar(64) NOT NULL,
  profile_version int NOT NULL DEFAULT 1,
  selection_mode varchar(16) NOT NULL DEFAULT 'AUTO',
  universe_scope varchar(32) NOT NULL DEFAULT 'CN_A_ALL',
  status varchar(32) NOT NULL DEFAULT 'QUEUED',
  result_summary text,
  warning_messages json DEFAULT NULL,
  warning_count int NOT NULL DEFAULT 0,
  universe_count int NOT NULL DEFAULT 0,
  seed_count int NOT NULL DEFAULT 0,
  candidate_count int NOT NULL DEFAULT 0,
  selected_count int NOT NULL DEFAULT 0,
  publish_count int NOT NULL DEFAULT 0,
  context_meta json DEFAULT NULL,
  started_at datetime DEFAULT NULL,
  completed_at datetime DEFAULT NULL,
  created_by varchar(64) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (run_id),
  UNIQUE KEY uk_stock_selection_runs_job_id (job_id),
  KEY idx_stock_selection_runs_trade_date (trade_date),
  KEY idx_stock_selection_runs_status (status, trade_date),
  KEY idx_stock_selection_runs_profile (profile_id, profile_version),
  CONSTRAINT fk_stock_selection_runs_profile_id FOREIGN KEY (profile_id) REFERENCES stock_selection_profiles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_selection_run_stage_logs (
  id varchar(64) NOT NULL,
  run_id varchar(64) NOT NULL,
  stage_key varchar(32) NOT NULL,
  stage_order int NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'PENDING',
  input_count int NOT NULL DEFAULT 0,
  output_count int NOT NULL DEFAULT 0,
  duration_ms bigint NOT NULL DEFAULT 0,
  detail_message text,
  payload_snapshot json DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_selection_run_stage_logs_run_stage (run_id, stage_key),
  KEY idx_stock_selection_run_stage_logs_run_id (run_id),
  CONSTRAINT fk_stock_selection_run_stage_logs_run_id FOREIGN KEY (run_id) REFERENCES stock_selection_runs (run_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_selection_run_candidates (
  id varchar(64) NOT NULL,
  run_id varchar(64) NOT NULL,
  symbol varchar(32) NOT NULL,
  name varchar(128) NOT NULL,
  stage varchar(32) NOT NULL,
  quant_score decimal(10,4) NOT NULL DEFAULT 0,
  risk_level varchar(16) NOT NULL DEFAULT 'MEDIUM',
  selected tinyint(1) NOT NULL DEFAULT 0,
  rank_no int NOT NULL DEFAULT 0,
  reason_summary varchar(512) DEFAULT NULL,
  factor_breakdown_json json DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_selection_run_candidates_run_symbol_stage (run_id, symbol, stage),
  KEY idx_stock_selection_run_candidates_run_stage (run_id, stage, rank_no),
  KEY idx_stock_selection_run_candidates_selected (run_id, selected),
  CONSTRAINT fk_stock_selection_run_candidates_run_id FOREIGN KEY (run_id) REFERENCES stock_selection_runs (run_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_selection_run_portfolio (
  id varchar(64) NOT NULL,
  run_id varchar(64) NOT NULL,
  symbol varchar(32) NOT NULL,
  name varchar(128) NOT NULL,
  rank_no int NOT NULL DEFAULT 0,
  quant_score decimal(10,4) NOT NULL DEFAULT 0,
  risk_level varchar(16) NOT NULL DEFAULT 'MEDIUM',
  weight_suggestion varchar(64) DEFAULT NULL,
  reason_summary varchar(512) DEFAULT NULL,
  factor_breakdown_json json DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_stock_selection_run_portfolio_run_symbol (run_id, symbol),
  KEY idx_stock_selection_run_portfolio_run_rank (run_id, rank_no),
  CONSTRAINT fk_stock_selection_run_portfolio_run_id FOREIGN KEY (run_id) REFERENCES stock_selection_runs (run_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
